import { v4 as uuidv4 } from "uuid";

export const eventCategoryData = {
  categories: [
    {
      id: uuidv4(),
      title: "Category 1",
      imgSrc: "/assets/img2.jpeg",
      events: [
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
      ],
    },
    {
      id: uuidv4(),
      title: "Category 2",
      imgSrc: "/assets/img5.jpeg",
      events: [
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img2.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img2.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img2.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img2.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img2.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img2.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img2.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img2.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img2.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img2.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img2.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img2.jpeg",
        },
      ],
    },
    {
      id: uuidv4(),
      title: "Category 3",
      imgSrc: "/assets/img2.jpeg",
      events: [
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img3.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img3.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img3.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img3.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img3.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img3.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img3.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img3.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img3.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img3.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img3.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img3.jpeg",
        },
      ],
    },
    {
      id: uuidv4(),
      title: "Category 4",
      imgSrc: "/assets/img5.jpeg",
      events: [
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img4.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img4.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img4.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img4.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img4.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img4.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img4.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img4.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img4.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img4.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img4.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img4.jpeg",
        },
      ],
    },
    {
      id: uuidv4(),
      title: "Category 5",
      imgSrc: "/assets/img2.jpeg",
      events: [
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
      ],
    },
    {
      id: uuidv4(),
      title: "Category 6",
      imgSrc: "/assets/img5.jpeg",
      events: [
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
        {
          id: uuidv4(),
          title: "Will India win more than 20 medals in the Olympics 2020 ?",
          volume: "30000",
          yes: "7",
          no: "4",
          imgSrc: "/assets/img1.jpeg",
        },
      ],
    },
  ],
};
